// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCO590M-lD8JdHHo3z2azoKa6d-2DBAfKE',
    appId: '1:31100701763:web:b5450ff4f9544e3e5d58f6',
    messagingSenderId: '31100701763',
    projectId: 'todavenda-prod',
    authDomain: 'todavenda-prod.firebaseapp.com',
    storageBucket: 'todavenda-prod.appspot.com',
    measurementId: 'G-ECPBGQ6HWP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBk76HDnJsvATD4ttE0N8ceylUwz_l1CaA',
    appId: '1:31100701763:android:83a347e0ad7dddde5d58f6',
    messagingSenderId: '31100701763',
    projectId: 'todavenda-prod',
    storageBucket: 'todavenda-prod.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJJOeCp6hVyNa2tgcYtemDFLFywhLCzyc',
    appId: '1:31100701763:ios:3f7e348ea33d6bfe5d58f6',
    messagingSenderId: '31100701763',
    projectId: 'todavenda-prod',
    storageBucket: 'todavenda-prod.appspot.com',
    iosClientId: '31100701763-ic5vi9qb8fa0dqqi8e7mffr4iakt9cl7.apps.googleusercontent.com',
    iosBundleId: 'com.leandrofabianjr.todavenda',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJJOeCp6hVyNa2tgcYtemDFLFywhLCzyc',
    appId: '1:31100701763:ios:7fcd118985baab655d58f6',
    messagingSenderId: '31100701763',
    projectId: 'todavenda-prod',
    storageBucket: 'todavenda-prod.appspot.com',
    iosClientId: '31100701763-oa8fu8nt63o2pd3iv9re1ngvvla60ccr.apps.googleusercontent.com',
    iosBundleId: 'com.leandrofabianjr.todavenda.RunnerTests',
  );
}
